name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: production
  NEXT_PUBLIC_BASE_PATH: /5x5_web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Clean install dependencies
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Cleaning previous installations..."
          rm -rf node_modules package-lock.json .next out
          echo "Installing dependencies..."
          npm install --production=false
          echo "Verifying Tailwind installation..."
          npm list tailwindcss postcss autoprefixer
      
      - name: Build with Next.js
        run: |
          echo "Starting build..."
          NODE_OPTIONS="--max_old_space_size=4096" npm run build
          echo "Build complete. Checking output:"
          ls -la out/
          echo "Ensuring .nojekyll exists"
          touch out/.nojekyll
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /5x5_web
          SITE_URL: https://nkumar23.github.io/5x5_web
      
      - name: Fix permissions
        run: |
          chmod -c -R +rX "out/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 