name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_ENV: production
  NEXT_PUBLIC_BASE_PATH: /5x5_web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -rf .next
          npm install
          npm install tailwindcss@latest postcss@latest autoprefixer@latest --save-dev
      
      - name: List directory structure
        run: |
          echo "Project structure:"
          ls -R src/
          echo "Node modules:"
          ls -la node_modules/tailwindcss
      
      - name: Build with Next.js
        run: |
          echo "Starting build..."
          NODE_OPTIONS="--max_old_space_size=4096" npm run build
          echo "Build complete. Checking output:"
          ls -la out/
        env:
          NODE_ENV: production
          NEXT_PUBLIC_BASE_PATH: /5x5_web
          SITE_URL: https://nkumar23.github.io/5x5_web
      
      - name: Fix permissions
        run: |
          chmod -c -R +rX "out/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 